### ISSUE TITLE
readAsDataURL returns wrong data when chunked

### ISSUE THREAD

**Issue by gadlol** [SaneMethod/HUp#4]
readAsDataURL returns wrong event.target.result WHEN we use the DeferReader AND we use the chunked option to true AND the type is image (perhaps the same problem for other types).

The problem is that it does not add the file type in the data string:

data:;base64,lVKENsd8bVZG7K2wAI+zQb/jiqpV2l9Z/hIoaAbV+.......

it should be

data:image/jpeg;base64,lVKENsd8bVZG7K2wAI+zQb/jiqpV2l9Z/hIoaAbV+.......

That problem in Chrome.

In Firefox we get:

data:application/octet-stream;base64,NGmHgRJvqzLVtN01ULFQkB/.......

which is again wrong. I guess Firefox auto adds "application/octet-stream"

So there is something wrong with the DeferReader when chunked option is true.

P.S. When we don't use chunked then it works fine as it should be.

**Comment by SaneMethod** [comment]
Good catch, should be fixed now. 
Note that there is still, of course, some assembly-required when it comes to the returned file chunks - if you're using readAsDataUrl, you'll want to remove the ```data:mime/type:base64,``` portion of the ```read_result``` for all read results beyond the first, so that you can successfully append them back together. You may also need to be aware of, and strip, padding characters ```=``` from the base64-encoded strings, other than the last one.

**Comment by SaneMethod** [comment]
On further thought, you may also need to consider the values at the boundaries and potentially alter their base64 representation to successfully re-combine a file read in chunks as a data-uri. To avoid this complexity, I'd suggest ```readAsArrayBuffer``` instead, as it is much simpler to concatenate the resulting array buffers - if you need a URL (say, to display an image preview), you can [put the concatenated arraybuffer into a blob and create an object url](https://developer.mozilla.org/en/docs/Web/API/Blob#Example_for_creating_a_URL_to_a_typed_array_using_a_blob).

If you need to be able to store the result of a file read as a string, I'd suggest reading as a data uri without chunking, or converting arraybuffers to a binary string/base64. You could also use ```readAsBinaryString```, but while most major browsers still support it, it is considered deprecated.

**Comment by SaneMethod** [comment]
I've had time to take another look at this, and you can now use readAsDataURL and get the expected chunks out. You'll need to reassemble said chunks to use the dataURL, of course, so I've added a new convenience function to the HUp instance for this purpose - take a look at the documentation for more details.
